train:
  realisation: data/SI_diag_g10_s10/train_realisations.npy
  param: data/SI_diag_g10_s10/train_param_labels.npy 

test:
  realisation: data/SI_diag_g10_s10/test_realisations.npy
  param: data/SI_diag_g10_s10/test_param_labels.npy

dataset_folder: data/SI_diag_g10_s10
grid_size: 10
num_steps: 10
num_sims_per_param: 20
generation_seed: 0
train_prop: 0.9
neighbourhood: "diagonal"


get_abm_fn: abm.spatial_compartmental.si.get_abm
abm_summary_stats:
  start: 1
  end: 2 #Exclusive Bound

parameters:
  p_infect: 
    low: 0.01
    high: 0.801 #Exclusive Bound
    step_size: 0.0098

n_initials:
  infected:
    low: 0.01
    high: 0.801 #Exclusive Bound
    step_size: 0.0098



